### ISSUE TITLE
Curious about rail utils 

### ISSUE THREAD

**Issue by bitmold** [dhruvkar/tracktrace#2]
I was wondering why in the definition of 
`LETTERS​ ​=​ {...` the value assigned to 'A' is 2 less than 'B', and that for every subsequent letter after B the numbers increase by 1. Was this intentional, and if so why?

**Comment by dhruvkar** [comment]
Sure. This is a calculation to output the "check digit", which is the last digit in a container number. The code follows the [ISO 6346 standard](https://en.wikipedia.org/wiki/ISO_6346#Check_digit) to calculate this. It was intentional since it's following a standard. Hope that helps!

**Comment by bitmold** [comment]
It does, thank you! When I just wrote this I was working through the code visually on my phone without actually running it/viewing it in an editor. I appreciate your fast response and also apologize for taking up your time with a superfluous comment.
